xyzz/acquisition

src/buyoutmanager.cpp, src/buyoutmanager.h, src/column.cpp, src/column.h, src/mainwindow.cpp, src/search.cpp, src/util.cpp, src/util.h
It's been a while since I touched in C++, so if my code is outside the rules, no problem correcting me :)
=> Added buyout age feature, fix #17

src/autoonline.cpp, src/modlist.cpp
MacOS build requires QProcess
And added a couple of missing filters that I use
=> Fixed auto-online for MacOS

acquisition.pro, forms/mainwindow.ui, src/application.cpp, src/application.h, src/currencymanager.cpp, src/currencymanager.h, src/datamanager.cpp, src/datamanager.h, src/itemsmanagerworker.cpp, src/itemsmanagerworker.h, src/mainwindow.cpp, src/mainwindow.h
Split the code in 4 commits : 568eada for the backend, 8de91fc for the GUI (didn't used the QT Editor because i'm terrible with it),  and d1845bc & a48cbee a couple of functionality i find useful because i like numbers.
Not used to submitting code, hope it meets the requirement of acquisition (also, feel free to modify the licence header if you want, not sure of what to write here).
=> Simple currency manager

src/currencymanager.cpp
=> Fixes #121

src/application.cpp, src/application.h, src/itemsmanager.cpp, src/itemsmanager.h, src/itemsmanagerworker.cpp, src/itemsmanagerworker.h, src/mainwindow.cpp, src/shop.cpp, src/shop.h, src/util.cpp, src/util.h, test/testshop.cpp
=> Multiple shop fix

src/buyoutmanager.cpp, src/buyoutmanager.h, src/shop.cpp, src/shop.h
Fixes #126 
(sorry about the previous PR, i messed things a little with git)
=> Shop spoiler

src/autoonline.cpp, src/autoonline.h, src/mainwindow.cpp, src/mainwindow.h
Calls new method AutoOnline::SetOnlineUpdate on QCloseEvent.
=> Closes xyzz/acquisition#167

src/buyoutmanager.h
Is this sufficient? Please let me know if there is anything else that would need to be done.
=> Add currency vaal orb

src/shop.cpp, src/util.cpp, src/util.h
This should fix the issue #173. However if the forum thread title is already in a bad shape it will *fix* it.
=> Fix issue #173 about forum thread title encoding.

acquisition.pro, forms/mainwindow.ui, src/buyoutmanager.cpp, src/buyoutmanager.h, src/item.cpp, src/item.h, src/itemlocation.cpp, src/itemlocation.h, src/items_model.cpp, src/items_model.h, src/itemsmanager.cpp, src/itemsmanager.h, src/itemsmanagerworker.cpp, src/itemsmanagerworker.h, src/main.cpp, src/mainwindow.cpp, src/mainwindow.h, src/search.cpp, src/search.h, src/tabcache.cpp, src/tabcache.h, test/testitemsmanager.cpp
This pull request is mainly for a code review and to get feeback on the proposed new web caching and tab selection features.  I'll be happy to fix anything that doesn't fit in with your coding methodology.
Details of the changes are in the individual commits.
Just want to call out the few features not yet implemented here - these are minor but wanted to send the pull request before the weekend.
Still to be implemented:
- checked state is not yet saved to database
- Need to update throttling logic as many tabs will be retrieved from
cache and we don't want those to count against throttling limit such
that we get throttled early.
=> Tab selection and caching enhancements

.gitmodules, acquisition.pro, appveyor.yml, src/util.cpp
This pull is to experiment with inclusion of boost header only library.  It initially includes a single use of the join function.  We'll see what the travis fallout is.
=> Include boost header only library

src/itemsmanagerworker.cpp
=> Preserve active char when refreshing single char

src/bucket.cpp, src/bucket.h, src/column.cpp, src/column.h, src/items_model.cpp, src/items_model.h, src/mainwindow.cpp, src/search.cpp
Use QVariant for column value as it's sort and model friendly.
Resolves #266
Addresses #218, #109
=> Enable column sorting

src/buyoutmanager.cpp
Remove warnings that probably shouldn't be.
=> Don't allow invalid buyouts to be considered active

src/column.cpp
Fixes string column sorting such as corrupted column.
=> Fix bug with sorting default string case

src/items_model.cpp, src/search.cpp
Well, so much for usefulness of beta testing... I immediately ran into an out of bounds issue when switching between item/view tabs after having selected some items.
This is a preliminary fix that has not been tested a lot but seems to work.
=> Fix out of bounds issue

src/column.cpp
=> Use system text color for normal items

src/itemsmanager.cpp
=> Don't attempt to garbage collect item buyouts

forms/mainwindow.ui, src/application.cpp, src/itemlocation.h, src/itemsmanager.cpp, src/itemsmanager.h, src/itemsmanagerworker.cpp, src/itemsmanagerworker.h, src/logindialog.cpp, src/logindialog.h, src/main.cpp, src/mainwindow.cpp, src/mainwindow.h, src/tabcache.cpp, src/tabcache.h, src/util.cpp, src/util.h
- Resolves #383
- Fix some issues with tab synchronization and caching that could lead to a number of problems
- Enhance quality of error messages so it's more clear when GGG API issues are causing problems
=> Resolve iss388

src/item.cpp
=> Fix icon sizing problem with quad tabs

src/item.cpp, src/item.h, src/itemtooltip.cpp
=> Add talisman tier to item tooltip

.travis.yml
A test to see if upgrading to trusty works.
=> Try updating travis to use trusty

src/filters.cpp, src/filters.h, src/item.cpp, src/item.h, src/itemsmanager.cpp, src/itemsmanager.h, src/mainwindow.cpp, src/mainwindow.h, src/util.cpp
=> Add dynamic category (type) filter
